version: '3.7'

services:
  postgres:
    image: postgres
    container_name: dev-burguer-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=dev-burguer-db
    ports:
      - '5432:5432'